GET http://localhost:5255/games

###

GET http://localhost:5255/games/1



HTTP/1.1 200  - OK
connection: close
content-type: application/json; charset=utf-8
date: Sat, 20 Dec 2025 17:47:32 GMT
server: Kestrel
transfer-encoding: chunked

HTTP/1.1 200  - OK
connection: close
content-type: application/json; charset=utf-8
date: Sat, 20 Dec 2025 17:47:32 GMT
server: Kestrel
transfer-encoding: chunked